title: "Hengyu's Home"
description: "Personal homepage and notes by Hengyu Wang, an undergraduate student at Tongji University."
url: "https://hengyu0510.github.io"
baseurl: ""
permalink: /posts/:year-:month-:day-:title/

kramdown:
  math_engine: mathjax

exclude:
  - README.md
  - LICENSE
  - ruihong04.github.io-main/
